### ISSUE TITLE
Timestamps in master log files

### ISSUE THREAD

**Issue by RuslanKonno** [PolishookDavid/LAST_OCS#30]
For the log files ~/log/matlab_master... it would be useful to add some timestamps to the printouts.

**Comment by EastEriq** [comment]
As I said be careful what you wish for, however now implemented in `LAST_.Handle.report()`. The log file is not truly a log file but just the dump of stdout, but in it much of the text (not all) is produced by `report()` and `.reportError()` so that you'll have enough of it for begging me to remove them.
