### ISSUE TITLE
Unit.takeExposure in the slave session does update the object

### ISSUE THREAD

**Issue by noralinn** [PolishookDavid/LAST_OCS#4]
When slewing and getting more observations in the slave, the object and filename will correspond to the previous coordinates (before slewing).

**Comment by EastEriq** [comment]
Since we're moving away from leaving slave sessions visible to the users and accepting interactive commands (we use a Listener MasterMessenger in them), sending `Unit.takeExposure` from a slave becomes a rather theoretical exercise. Moreover, by now `Unit.UnitHeader` is generated in the master just after starting the exposure, instead of having the slaves query the mount at the end of the exposure.
Given all this, I close the issue as a WONTFIX.
